apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan1
spec:
  config: '{
            "cniVersion": "0.3.1",
            "type": "macvlan",
            "master": "enp0s3",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "172.30.1.0/24",
                         "rangeStart": "172.30.1.198",
                         "rangeEnd": "172.30.1.200",
                         "gateway": "172.30.1.254"
                    } ]
                ]
            }
        }'
