apiVersion: v1
kind: Service
metadata:
  name: sctp-lb1
  annotations:
    loxilb.io/num-secondary-networks: "2"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-test
  ports:
    - port: 55002
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-test
  labels:
    what: sctp-test
spec:
  containers:
    - name: sctp-test
      image: aweimeow/sctp-server
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      ports:
        - containerPort: 9999
