---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    frontend:
      max_outstanding_per_tenant: 2048

    pattern_ingester:
      enabled: true

    limits_config:
      max_global_streams_per_user: 0
      ingestion_rate_mb: 50000
      ingestion_burst_size_mb: 50000
      volume_enabled: true

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://localhost:9093

    analytics:
      reporting_enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
      external_labels:
        cluster: "prometheus-cluster"
        replica: "$(POD_NAME)"
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
        api_version: v2

    scrape_configs:
      - job_name: 'loxilb'
        metrics_path: /netlox/v1/metrics
        static_configs:
          - targets:
            - 'loxilb-lb-service.kube-system.svc.cluster.local:11111'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore
  namespace: monitoring
data:
  objstore.yml: |
    type: s3
    config:
      bucket: "prometheus"
      endpoint: "minio-service:9000"
      access_key: "minio"
      secret_key: "minio123"
      insecure: true
---
# ✅ MinIO Object Storage for Thanos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
          - "server"
          - "/data"
        env:
          - name: MINIO_ROOT_USER
            value: "minio"
          - name: MINIO_ROOT_PASSWORD
            value: "minio123"
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: minio-data
            mountPath: "/data"
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: monitoring
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/loki.yaml
          subPath: loki.yaml
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
          items:
            - key: loki.yaml
              path: loki.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: loki-llb
  namespace: monitoring
  annotations:
    loxilb.io/lbmode: "onearm"
    loxilb.io/liveness: "yes"
    loxilb.io/timeout: "36000"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: loki
  ports:
  - port: 59302
    targetPort: 3100
    protocol: TCP
---
# ✅ Prometheus HA + Thanos Sidecar
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceName: prometheus
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.min-block-duration=2h"
          - "--storage.tsdb.max-block-duration=2h"
        volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
      - name: thanos-sidecar
        image: quay.io/thanos/thanos:v0.37.2
        args:
          - sidecar
          - "--prometheus.url=http://localhost:9090"
          - "--objstore.config-file=/etc/thanos/objstore.yml"
          - "--tsdb.path=/prometheus"
          - "--grpc-address=0.0.0.0:10901"
        ports:
          - containerPort: 10901
            name: grpc
        volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus
          - name: thanos-config
            mountPath: /etc/thanos
      volumes:
        - name: prometheus-data
          emptyDir: {}
        - name: thanos-config
          configMap:
            name: thanos-objstore
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
---
# ✅ Thanos Sidecar Service for Prometheus (GRPC)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-thanos
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - port: 10901
      targetPort: 10901
      protocol: TCP
      name: grpc
---
# ✅ Thanos Querier for Aggregated Queries
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos-querier
        image: quay.io/thanos/thanos:v0.37.2
        args:
          - "query"
          - "--store=dnssrv+_grpc._tcp.prometheus-thanos.monitoring.svc.cluster.local"
          - "--http-address=0.0.0.0:9090"
          - "--query.replica-label=prometheus"
        ports:
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-service
  namespace: monitoring
spec:
  selector:
    app: thanos-querier
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-llb
  namespace: monitoring
  annotations:
    loxilb.io/lbmode: "onearm"
    loxilb.io/liveness: "yes"
    loxilb.io/timeout: "36000"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: thanos-querier
  ports:
  - port: 59303
    targetPort: 9090
    protocol: TCP
  sessionAffinity: None
